---
- name: Setup flask application

  tasks:
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
  - name: Install pip 
    apt:
      name: python3-pip 
  - name: Install requirements
    pip: 
      requirements: /vagrant/requirements.txt
  - name: Start flask application
    shell: "python3 -m flask run --host=0.0.0.0" 
    environment: 
      FLASK_APP: /vagrant/app.py
      